# Generated by Django 2.2.12 on 2021-02-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='article',
            field=models.CharField(help_text='артикул товара', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='model_name',
            field=models.CharField(help_text='модель', max_length=15),
        ),
    ]
