# Generated by Django 2.2.12 on 2020-06-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
