# Generated by Django 2.2.17 on 2020-12-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0002_avangarsstock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvangarsStock',
            new_name='AvangardStock',
        ),
    ]
