# Generated by Django 2.2.12 on 2020-06-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0002_stores_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
