# Generated by Django 2.2.17 on 2020-12-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_auto_20201230_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeChasStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('count', models.SmallIntegerField()),
            ],
        ),
    ]
