# Generated by Django 2.2.12 on 2020-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_auto_20200621_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
