# Generated by Django 2.2.12 on 2021-02-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_alifeedoperations_alifeedoperationslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alifeedoperations',
            name='jobID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
