# Generated by Django 2.2.17 on 2021-01-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0004_tradechasstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avangardstock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tradechasstock',
            name='id',
        ),
        migrations.AlterField(
            model_name='avangardstock',
            name='item',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tradechasstock',
            name='item',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
