# Generated by Django 2.2.12 on 2020-06-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0004_suppliers_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
