# Generated by Django 2.2.12 on 2021-02-09 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0004_auto_20210208_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='alifeedoperations',
            name='request_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
