# Generated by Django 2.2.12 on 2020-07-01 17:35

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0005_auto_20200621_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Каталог моделей'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
        migrations.AlterModelOptions(
            name='stores',
            options={'verbose_name': 'Складской запас', 'verbose_name_plural': 'Складские запасы'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name': 'поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='article',
            field=models.CharField(help_text='артикул товара', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='model_name',
            field=models.CharField(help_text='модель', max_length=20),
        ),
        migrations.AlterField(
            model_name='stores',
            name='catalog_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_of_store', to='crmApp.Catalog', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='quantity',
            field=models.IntegerField(blank=True, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items_of_supplier', to='crmApp.Suppliers', verbose_name='поставщик'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='wholesale_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='RUR', max_digits=14, verbose_name='оптовая цена'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Наименование поставщика'),
        ),
    ]
