# Generated by Django 2.2.17 on 2021-01-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0006_auto_20210109_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradechasstock',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradechasstock',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
