# Generated by Django 2.2.12 on 2020-09-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0006_auto_20200701_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_offline_date', models.DateTimeField(verbose_name='product offline time')),
                ('ws_display', models.CharField(max_length=8, verbose_name='product offline reason')),
                ('subject', models.CharField(max_length=150, verbose_name='product tite')),
                ('src', models.CharField(max_length=8, verbose_name='product src')),
                ('product_min_price', models.CharField(max_length=8, verbose_name='min price among all skus of the product')),
                ('product_max_price', models.CharField(max_length=8, verbose_name='max price among all skus of the product')),
                ('product_id', models.IntegerField(unique=True)),
                ('owner_member_seq', models.IntegerField(verbose_name='seller member seq')),
                ('owner_member_id', models.CharField(max_length=8, verbose_name='seller login id')),
                ('image_u_r_ls', models.URLField(verbose_name='product image url')),
                ('group_id', models.IntegerField()),
                ('gmt_modified', models.DateTimeField(verbose_name='time that product was modifed')),
                ('gmt_create', models.DateTimeField(verbose_name='time that product was created')),
                ('freight_template_id', models.IntegerField(verbose_name='freight template id')),
                ('currency_code', models.CharField(max_length=3, verbose_name='currency code')),
                ('coupon_start_date', models.DateTimeField(verbose_name='Coupon start date, GMT+8')),
                ('coupon_end_date', models.DateTimeField(verbose_name='Coupon end date, GMT+8')),
            ],
        ),
    ]
