# Generated by Django 2.2.12 on 2020-09-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0012_aliorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliorders',
            name='id',
        ),
        migrations.AlterField(
            model_name='aliorders',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='order ID'),
        ),
    ]
