# Generated by Django 2.2.12 on 2020-09-23 19:18

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0013_auto_20200922_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliorders',
            name='escrow_fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=7, max_length=8, null=True, verbose_name='escrow fee'),
        ),
        migrations.AlterField(
            model_name='aliorders',
            name='escrow_fee_rate',
            field=models.IntegerField(null=True, verbose_name='escrow fee rate'),
        ),
        migrations.AlterField(
            model_name='aliorders',
            name='loan_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=7, max_length=8, null=True, verbose_name='loan amount details'),
        ),
        migrations.AlterField(
            model_name='aliorders',
            name='pay_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=7, max_length=8, null=True, verbose_name='pay amount'),
        ),
    ]
