# Generated by Django 2.2.12 on 2020-09-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0014_auto_20200923_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliorders',
            name='gmt_pay_time',
            field=models.DateTimeField(null=True, verbose_name='order pay time'),
        ),
        migrations.AlterField(
            model_name='aliorders',
            name='gmt_send_goods_time',
            field=models.DateTimeField(null=True, verbose_name='Last order delivery time'),
        ),
    ]
