# Generated by Django 2.2.12 on 2020-09-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0015_auto_20200923_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliorders',
            name='timeout_left_time',
            field=models.IntegerField(null=True, verbose_name='The remain time of the current status '),
        ),
    ]
