# Generated by Django 2.2.12 on 2020-09-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0017_aliordersproductlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliordersproductlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='aliordersproductlist',
            name='child_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='child order id'),
            preserve_default=False,
        ),
    ]
