# Generated by Django 2.2.12 on 2020-09-26 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0018_auto_20200924_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliordersproductlist',
            name='main_order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crmApp.AliOrders'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aliordersproductlist',
            name='child_id',
            field=models.IntegerField(verbose_name='child order id'),
        ),
        migrations.AlterField(
            model_name='aliordersproductlist',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='sub order id '),
        ),
    ]
