# Generated by Django 2.2.12 on 2020-09-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0021_auto_20200926_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliproducts',
            name='ws_display',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='product offline reason'),
        ),
    ]
