# Generated by Django 2.2.12 on 2020-09-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0022_auto_20200926_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliproducts',
            name='product_max_price_currency',
        ),
        migrations.RemoveField(
            model_name='aliproducts',
            name='product_min_price_currency',
        ),
        migrations.AlterField(
            model_name='aliproducts',
            name='product_max_price',
            field=models.CharField(max_length=10, verbose_name='max price among all skus of the product'),
        ),
        migrations.AlterField(
            model_name='aliproducts',
            name='product_min_price',
            field=models.CharField(max_length=10, verbose_name='min price among all skus of the product'),
        ),
    ]
