# Generated by Django 2.2.12 on 2020-09-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0023_auto_20200928_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliproducts',
            name='product_max_price',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='max price among all skus of the product'),
        ),
        migrations.AlterField(
            model_name='aliproducts',
            name='product_min_price',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='min price among all skus of the product'),
        ),
    ]
