# Generated by Django 2.2.12 on 2020-10-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0024_auto_20200930_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliGroupList',
            fields=[
                ('group_name', models.CharField(max_length=20, verbose_name='group name')),
                ('group_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='group id')),
            ],
        ),
        migrations.AlterField(
            model_name='aliorders',
            name='escrow_fee_rate',
            field=models.PositiveIntegerField(null=True, verbose_name='escrow fee rate'),
        ),
        migrations.AlterField(
            model_name='aliorders',
            name='order_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='order ID'),
        ),
        migrations.AlterField(
            model_name='aliordersproductlist',
            name='child_id',
            field=models.PositiveIntegerField(verbose_name='child order id'),
        ),
        migrations.AlterField(
            model_name='aliordersproductlist',
            name='goods_prepare_time',
            field=models.PositiveIntegerField(verbose_name='goods prepare days'),
        ),
        migrations.AlterField(
            model_name='aliordersproductlist',
            name='order_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='sub order id '),
        ),
        migrations.AlterField(
            model_name='aliordersproductlist',
            name='product_count',
            field=models.PositiveIntegerField(verbose_name='product count'),
        ),
        migrations.AlterField(
            model_name='aliproducts',
            name='freight_template_id',
            field=models.PositiveIntegerField(verbose_name='freight template id'),
        ),
        migrations.AlterField(
            model_name='aliproducts',
            name='group_id',
            field=models.IntegerField(verbose_name='Search field by product groups. Enter product group id (groupId)'),
        ),
        migrations.AlterField(
            model_name='aliproducts',
            name='owner_member_seq',
            field=models.PositiveIntegerField(verbose_name='seller member seq'),
        ),
        migrations.AlterField(
            model_name='aliproducts',
            name='product_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AliChildGroupList',
            fields=[
                ('group_name', models.CharField(max_length=20, verbose_name='group name')),
                ('group_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='group id')),
                ('ali_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmApp.AliGroupList')),
            ],
        ),
    ]
