# Generated by Django 2.2.12 on 2020-10-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0025_auto_20201001_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='aligrouplist',
            name='hasChild',
            field=models.BooleanField(default=False, verbose_name='item has subgroup'),
        ),
    ]
