# Generated by Django 2.2.12 on 2020-10-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0026_aligrouplist_haschild'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliproducts',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
