# Generated by Django 2.2.12 on 2020-10-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0030_remove_aliproducts_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliorders',
            name='product_list',
        ),
    ]
