# Generated by Django 2.2.12 on 2020-10-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0031_remove_aliorders_product_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliorders',
            name='payment_type',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='pay type'),
        ),
    ]
