# Generated by Django 2.2.12 on 2020-11-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0032_auto_20201010_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliOrdersAddInformation',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crmApp.AliOrders')),
                ('buyer_info', models.CharField(max_length=100, verbose_name='buyer info')),
                ('gmt_modified', models.DateTimeField(null=True, verbose_name='modified time, US pacific time')),
                ('receipt_address', models.CharField(max_length=200, verbose_name='receipt address')),
                ('gmt_trade_end', models.DateTimeField(null=True, verbose_name='Order end time')),
                ('buyerloginid', models.CharField(max_length=30, verbose_name='buyer login id')),
                ('order_status', models.CharField(max_length=30, verbose_name='Order Status')),
            ],
        ),
        migrations.AlterField(
            model_name='aliordersproductlist',
            name='main_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_list', to='crmApp.AliOrders'),
        ),
    ]
