# Generated by Django 2.2.12 on 2020-11-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0034_aliordersaddinformation_coord'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliordersaddinformation',
            name='full_normalised_adress',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Нормализованный адрес'),
        ),
    ]
