# Generated by Django 2.2.12 on 2020-11-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0035_aliordersaddinformation_full_normalised_adress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AliOrdersAddInformation',
            new_name='AliOrdersDetailedInformation',
        ),
    ]
