# Generated by Django 2.2.12 on 2020-11-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0036_auto_20201123_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliordersdetailedinformation',
            name='gmt_create',
            field=models.DateTimeField(null=True, verbose_name='время создания заказа'),
        ),
    ]
