# Generated by Django 2.2.12 on 2020-11-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0037_aliordersdetailedinformation_gmt_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliordersdetailedinformation',
            old_name='full_normalised_adress',
            new_name='normalised_adress',
        ),
    ]
