# Generated by Django 2.2.12 on 2020-11-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0038_auto_20201123_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliordersdetailedinformation',
            name='normalised_adress',
        ),
        migrations.AddField(
            model_name='aliordersdetailedinformation',
            name='normalised_address',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Нормализованный адрес'),
        ),
    ]
