# Generated by Django 2.2.12 on 2020-11-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0039_auto_20201123_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliordersdetailedinformation',
            name='pvz',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='СДЕК ПВЗ в городе покупателя'),
        ),
    ]
