# Generated by Django 2.2.12 on 2020-11-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0041_aliordersdetailedinformation_tarifes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliordersdetailedinformation',
            name='tarifes',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Тарифы СДЭК'),
        ),
    ]
