# Generated by Django 2.2.12 on 2020-11-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0042_auto_20201125_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliordersdetailedinformation',
            old_name='normalised_address',
            new_name='normalized_address',
        ),
    ]
