# Generated by Django 2.2.12 on 2020-12-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0043_auto_20201125_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliordersdetailedinformation',
            name='isPVZ',
            field=models.BooleanField(blank=True, default=True, verbose_name='Есть GDP в городе'),
        ),
    ]
