# Generated by Django 2.2.12 on 2020-12-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0044_aliordersdetailedinformation_ispvz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliordersdetailedinformation',
            name='isPVZ',
            field=models.BooleanField(blank=True, verbose_name='Есть ПВЗ в городе'),
        ),
    ]
