# Generated by Django 2.2.12 on 2020-12-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0047_auto_20201202_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliordersdetailedinformation',
            name='full_normalized_address',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Полный нормализованный адрес'),
        ),
    ]
