# Generated by Django 2.2.12 on 2020-12-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0048_aliordersdetailedinformation_full_normalized_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliordersdetailedinformation',
            name='cdek_response',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ от СДЭК'),
        ),
        migrations.AddField(
            model_name='aliordersdetailedinformation',
            name='cdek_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Статус посылки СДЭК'),
        ),
    ]
