# Generated by Django 2.2.12 on 2020-12-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0049_auto_20201209_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliordersdetailedinformation',
            old_name='cdek_response',
            new_name='cdekResponse',
        ),
        migrations.RenameField(
            model_name='aliordersdetailedinformation',
            old_name='cdek_status',
            new_name='cdekStatus',
        ),
    ]
