# Generated by Django 2.2.12 on 2020-12-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0050_auto_20201209_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokensApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameApi', models.CharField(max_length=10, verbose_name='API имя')),
                ('token', models.CharField(max_length=250, null=True, verbose_name='Токен')),
                ('expires_in', models.IntegerField(null=True, verbose_name='Срок действия токена')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='Время получения токена')),
            ],
        ),
    ]
