# Generated by Django 2.2.12 on 2020-12-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0051_tokensapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokensapi',
            name='id',
        ),
        migrations.AlterField(
            model_name='tokensapi',
            name='nameApi',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='API имя'),
        ),
    ]
