# Generated by Django 2.2.12 on 2020-12-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0052_auto_20201209_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokensapi',
            name='token',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Токен'),
        ),
    ]
