# Generated by Django 2.2.12 on 2020-12-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0053_auto_20201209_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliordersdetailedinformation',
            name='isPVZ',
            field=models.PositiveIntegerField(null=True, verbose_name='Есть ПВЗ в городе'),
        ),
        migrations.AlterField(
            model_name='tokensapi',
            name='expires_in',
            field=models.PositiveIntegerField(null=True, verbose_name='Срок действия токена'),
        ),
    ]
