# Generated by Django 2.2.12 on 2020-12-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0054_auto_20201213_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokensapi',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='tokensapi',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='tokensapi',
            name='data_expires',
            field=models.DateTimeField(null=True, verbose_name='Дата действия токена'),
        ),
    ]
