# Generated by Django 2.2.12 on 2020-07-29 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='content',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='contents_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
