# Generated by Django 2.2.12 on 2020-05-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
